#!/bin/bash
M_SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
CURR_DIR=$PWD
source $M_SCRIPT_DIR/../common_functions.sh
start=`date +%s`
clean_up () {
    ARG=$?
    if [[ ${CW_DEBUG_KEEP_FILES+defined} ]];then 
        if [[ ${CW_BUILD_TMPDIR+defined} ]];then
            print_err "Build files can be found at $CW_BUILD_TMPDIR, and $_usr_yaml"
        else
            print_err "Program failed before any build files were created"    
        fi
    else
        test -f "$_usr_yaml" && rm "$_usr_yaml"
        test -d "$CW_BUILD_TMPDIR" && rm -r "$CW_BUILD_TMPDIR"
        print_err "Set CW_DEBUG_KEEP_FILES env variable to keep build files"
    fi
    kill  -- -$$ &>/dev/null
    exit $ARG
}
trap clean_up err
trap clean_up INT
# Here some stuff for more robust python
export _usr_yaml="$(mktemp)";
if [[ ! ${CW_GLOBAL_YAML+defined} ]];then
    export CW_GLOBAL_YAML=$M_SCRIPT_DIR/../default_config/config.yaml
fi

# We might need to dynamically set values
python3 $M_SCRIPT_DIR/scripts/cont-conda.py "$@" || { print_err "Failed parsing input" ; false ;}
if [[ ! -s "$_usr_yaml" ]];then
    test -f $_usr_yaml && rm $_usr_yaml
    # Probably printed the help message
    exit 0
fi
print_info "Parsing input" 1
print_info "Calling frontend $M_SCRIPT_DIR/$0" 2
print_info "Parsing user and default configs " 2
CW_BUILD_TMPDIR=$(python3 $M_SCRIPT_DIR/../construct.py $CW_GLOBAL_YAML $_usr_yaml) \
    || { print_err "Configuration construction failed" ; false ;}
export CW_BUILD_TMPDIR


source $CW_BUILD_TMPDIR/_vars.sh
if [[ ! -d "$CW_INSTALLATION_PREFIX" ]];then
    print_err "Installation dir $CW_INSTALLATION_PREFIX does not exist"  ; false
fi

$M_SCRIPT_DIR/../pre.sh || { print_err "Failed getting container image"; false ;}
$M_SCRIPT_DIR/../create_inst.sh || { print_err "Installation failed" ; false ;} 
$M_SCRIPT_DIR/../generate_wrappers.sh || { print_err "Wrapper generation failed"; false ;}
$M_SCRIPT_DIR/../post.sh || { print_err "Failed to move to install dir"; false ; }
test -f "$_usr_yaml" && rm "$_usr_yaml"
end=`date +%s`
print_info "Done, duration: $((end-start))s" 1

