#!/bin/bash
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
M_SCRIPT_DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"

calling_name=$(basename $0)
CURR_DIR=$PWD
source $M_SCRIPT_DIR/../common_functions.sh
source $M_SCRIPT_DIR/inst_vars.sh
start=`date +%s`
clean_up () {
    trap '' 2
    ARG=$?
    if [[ ${CW_DEBUG_KEEP_FILES+defined} ]];then 
        if [[ ${CW_BUILD_TMPDIR+defined} ]];then
            print_err "Build files can be found at $CW_BUILD_TMPDIR, and $_usr_yaml"
        else
            print_err "Program failed before any build files were created"    
        fi
    else
        test -f "$_usr_yaml" && rm "$_usr_yaml"
        test -d "$CW_BUILD_TMPDIR" && rm -r "$CW_BUILD_TMPDIR"
        print_err "Set CW_DEBUG_KEEP_FILES env variable to keep build files"
    fi
    trap 2
    kill  -- -$$ &>/dev/null
    exit $ARG
}
export _usr_yaml="$(mktemp /tmp/cw-tmp.XXXXXX )";
trap clean_up err
trap clean_up INT
if [[ ! ${CW_GLOBAL_YAML+defined} ]];then
    export CW_GLOBAL_YAML=$M_SCRIPT_DIR/../default_config/config.yaml
fi
print_info "Calling frontend $( basename $SOURCE )" 2
print_info "Calling parsers script $calling_name " 2
print_info "Using $(readlink -f $CW_GLOBAL_YAML) as default config" 2

# We might need to dynamically set values
export SAVE_PP=$PYTHONPATH
unset PYTHONPATH
$PY_EXE $M_SCRIPT_DIR/$calling_name.py "$@" || exit $? 
if [[ ! -s "$_usr_yaml" ]];then
    test -f $_usr_yaml && rm $_usr_yaml
    # Probably printed the help message
    exit 0
fi


print_info "Constructing configuration" 1
print_info "Parsing user and default configs " 2
CW_BUILD_TMPDIR=$($PY_EXE $M_SCRIPT_DIR/../construct.py $CW_GLOBAL_YAML $_usr_yaml) \
    || { print_err "Configuration construction failed" ; false ;}
export CW_BUILD_TMPDIR
export PYTHONPATH=$SAVE_PP

source $CW_BUILD_TMPDIR/_vars.sh
if [[ ! -d "$CW_INSTALLATION_PREFIX" ]];then
    print_err "Installation dir $CW_INSTALLATION_PREFIX does not exist"  ; false
fi
if [[ ! -w "$CW_INSTALLATION_PREFIX" || ! -x "$CW_INSTALLATION_PREFIX" ]];then
    print_err "Installation dir $CW_INSTALLATION_PREFIX is not writable"  ; false
fi

if [[ "$(umask)" == "0007" ]];then
    print_info "Umask is 0007" 2
    chmod g+rwx $CW_BUILD_TMPDIR
    chmod o-rwx $CW_BUILD_TMPDIR
elif [[ "$(umask)" == "0002"  ]];then
    print_info "Umask is 0002" 2
    chmod g+rwx $CW_BUILD_TMPDIR
    chmod o+rx $CW_BUILD_TMPDIR
elif [[ "$(umask)" == "0022"  ]];then
    print_info "Umask is 0022" 2
    chmod go+rx $CW_BUILD_TMPDIR
else
   print_warn "Umask set to $CW_UMASK, check permissions of finished installation" 
fi
chmod g+s $CW_BUILD_TMPDIR
chgrp $(stat -c "%G" $CW_INSTALLATION_PREFIX ) $CW_BUILD_TMPDIR


$M_SCRIPT_DIR/../pre.sh || { print_err "Failed getting container image"; false ;}
# Nothing to do if we are just wrapping a container
if [[ ! "$CW_MODE" == "wrapcont" ]];then
    $M_SCRIPT_DIR/../create_inst.sh || { print_err "Installation failed" ; false ;} 
fi

if [[ "$CW_CREATE_WRAPPERS" == "yes"  ]]; then
    $M_SCRIPT_DIR/../generate_wrappers.sh || { print_err "Wrapper generation failed"; false ;}
fi
$M_SCRIPT_DIR/../post.sh || { print_err "Failed to move to install dir"; false ; }
test -f "$_usr_yaml" && rm "$_usr_yaml"
end=`date +%s`
print_info "Done, duration: $((end-start))s" 1

