#!/bin/bash
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
M_SCRIPT_DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"

calling_name=$(basename $0)
CURR_DIR=$PWD
source $M_SCRIPT_DIR/../common_functions.sh
start=`date +%s`
clean_up () {
    trap '' 2
    ARG=$?
    if [[ ${CW_DEBUG_KEEP_FILES+defined} ]];then 
        if [[ ${CW_BUILD_TMPDIR+defined} ]];then
            print_err "Build files can be found at $CW_BUILD_TMPDIR, and $_usr_yaml"
        else
            print_err "Program failed before any build files were created"    
        fi
    else
        test -f "$_usr_yaml" && rm "$_usr_yaml"
        rm -r "$CW_BUILD_TMPDIR"
        print_err "Set CW_DEBUG_KEEP_FILES env variable to keep build files"
    fi
    trap 2
    kill  -- -$$ &>/dev/null
    exit $ARG
}
# Here some stuff for more robust python
export _usr_yaml="$(mktemp)";
if [[ ! ${CW_GLOBAL_YAML+defined} ]];then
    export CW_GLOBAL_YAML=$M_SCRIPT_DIR/../default_config/config.yaml
fi
print_info "Calling frontend $( basename $SOURCE )" 2
print_info "Calling parsers script $calling_name " 2

# We might need to dynamically set values
python3 $M_SCRIPT_DIR/scripts/$calling_name.py "$@" || exit $? 
if [[ ! -s "$_usr_yaml" ]];then
    test -f $_usr_yaml && rm $_usr_yaml
    # Probably printed the help message
    exit 0
fi
trap clean_up err
trap clean_up INT
print_info "Parsing input" 1
print_info "Parsing user and default configs " 2
CW_BUILD_TMPDIR=$(python3 $M_SCRIPT_DIR/../construct.py $CW_GLOBAL_YAML $_usr_yaml) \
    || { print_err "Configuration construction failed" ; false ;}
export CW_BUILD_TMPDIR


source $CW_BUILD_TMPDIR/_vars.sh
if [[ ! -d "$CW_INSTALLATION_PREFIX" ]];then
    print_err "Installation dir $CW_INSTALLATION_PREFIX does not exist"  ; false
fi

$M_SCRIPT_DIR/../pre.sh || { print_err "Failed getting container image"; false ;}
# Nothing to do if we are just wrapping a container
if [[ ! "$CW_MODE" == "wrapcont" ]];then
    $M_SCRIPT_DIR/../create_inst.sh || { print_err "Installation failed" ; false ;} 
fi

if [[ "$CW_CREATE_WRAPPERS" == "yes"  ]]; then
    $M_SCRIPT_DIR/../generate_wrappers.sh || { print_err "Wrapper generation failed"; false ;}
fi
$M_SCRIPT_DIR/../post.sh || { print_err "Failed to move to install dir"; false ; }
test -f "$_usr_yaml" && rm "$_usr_yaml"
end=`date +%s`
print_info "Done, duration: $((end-start))s" 1

