
# Value will be selected if no user provided value
# Otherwise ignored
defaults:
    log_level: 2
    env_name: env1 
    conda_version: latest
    installation_prefix: $PWD
    installation_path: "/LOCAL_TYKKY"
    # if this is not a thing which exist
    # I will do a singularity pull
    container_src: 'docker://rockylinux:8.9'
    # name of the container image when on disk
    container_image: container.sif 
    sqfs_image: img.sqfs 
    source_mount_point: /TMP_MP 
    composable: true
    mount_points:
            - /tmp
            - /home
            - /run
    isolate: no
    create_wrappers: yes
    wrap_all: no
    num_cpus: 4
    sqfs_options: "-noappend"
    add_ld: yes
force:
    # I will create some random dir under here 
    build_tmpdir_base: $PWD
    conda_arch: 'Linux-x86_64'
    max_num_cpus: 4
    # No logic currently to refer to other variables here
    # So either implement that, throw them to $TMPDIR 
    workdir: $PWD   
    # What executable name or path to use for singularity
    # For fully dynamic behavior 
    # You can just set singularity or apptainer here.
    # Keep in mind that this could break installations
    # if e.g the user installs singularity via conda
    # when user namespaces are not enabled 
    # Environment variables can be used here 
    # but they will be expanded during build,
    # not during runtime
    singularity_executable_path: "singularity"
    
# Value will override any user set value

# Value will be appendend to user defined list 
appends:

# Value will be prepended to user defined list
prepends:
