# Anything which is a path is relative to the 
# installation dir of this tool.

# Value will be selected if no user provided value
# Otherwise ignored
defaults:
    log_level: 1
    conda_version: latest
    env_name: env1 
    installation_prefix: $PWD
    installation_path: "/CSC_CONTAINER"
    # if this is not a thing which exist
    # I will do a singularity pull
    container_src: 'library://centos:7.9'
    # name of the container image when on disk
    container_image: container.sif 
    sqfs_image: img.sqfs 
    source_mount_point: /TMP_MP 
    isolate: no
    create_wrappers: yes
    wrap_all: no
    keep_tmpdir: no
    sqfs_options: ""
    add_ld: yes
    
    template: conda
    # new vs inplace
    update_mode: new
force:
    # I will create some random dir under here 
    build_tmpdir_base: $TMPDIR
    conda_arch: 'Linux-x86_64'
    
# Value will override any user set value

# Value will be appendend to user defined list 
appends:

# Value will be prepended to user defined list
prepends:


